name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Run only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Validate HTML
      - name: Validate HTML
        run: npx html-validator-cli "index.html"

      # Step 4: Check for broken links
      - name: Check links
        run: npx broken-link-checker http://localhost:8080 --recursive

      # Step 5: Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
